# Generated by Django 4.0.3 on 2022-08-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operator', models.CharField(max_length=10)),
                ('Circle', models.CharField(max_length=30)),
                ('Plan_type', models.CharField(max_length=10)),
                ('Data', models.CharField(max_length=20)),
                ('Validity', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=30)),
            ],
        ),
    ]
